# 保存照片和视频缩略图的路径
DataPath: "./data"

# 是否通过高德地图 api 获取地理位置, 如果 AMapKey 为空，则程序会自动将该值设为 false
GPSToGeo: true

#  高德地图 key
AMapKey: ""

# 照片的扩展名列表，小写
PhotoExtList: [".jpg", ".jpeg", ".png", ".gif"]

# 视频的扩展名列表，小写
VideoExtList: [".mp4", ".mov"]

# Web 服务监听的地址
HTTPAddr: 127.0.0.1

# Web 服务监听的端口号
HTTPPort: 80
